#SPDX-License-Identifier: MIT-0
---
# tasks file for pgadmin
- name: generate docker compose file
  template:
    src: pgadmin-compose.yml.j2
    dest: /home/{{ ansible_user }}/pgadmin-compose.yml
    mode: '0644'

- name: start pgadmin stack
  command:
    cmd: docker-compose -f /home/{{ ansible_user }}/pgadmin-compose.yml up -d
