#SPDX-License-Identifier: MIT-0
---
# defaults file for odoo

odoo_name: odoo
odoo_image: odoo:latest
odoo_port: 8069
odoo_volume_name: odoo-data
odoo_database_name: postgres
db_image: postgres:18-alpine
db_name: postgres
db_user: odoo
db_password: odoo
network_name: "{{ network_name }}"
