#SPDX-License-Identifier: MIT-0
---
# tasks file for odoo
- name: generate docker compose file
  template:
    src: odoo-compose.yml.j2
    dest: /home/{{ ansible_user }}/odoo-compose.yml
    mode: "0555"

- name: start odoo stack
  command:
    cmd: "docker-compose -f /home/{{ ansible_user }}/odoo-compose.yml up -d"
