#SPDX-License-Identifier: MIT-0
---
# tasks file for docker
- name: update system
  apt:
    update_cache: yes
    upgrade: dist
  become: yes

- name: download docker install script
  get_url:
    url: https://get.docker.com
    dest: /tmp/install-docker.sh
    mode: 0755

- name: install docker
  command:
    cmd: sh /tmp/install-docker.sh
  become: yes

- name: start docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: check docker group exists
  group:
    name: docker
    state: present
  become: yes
  notify: restart docker service

- name: add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes
  notify: restart docker service
