#SPDX-License-Identifier: MIT-0
---
# defaults file for ic-webapp

docker_network: ic-webapp-network
icw_container_name: ic-webapp
icw_image: ulrichsteve/ic-webapp:1.0
icw_port: 8081
odoo_url: "http://{{ ansible_host }}:8069"
pgadmin_url: "http://{{ ansible_host }}:8082"
